<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>1a9061a3-8fc2-4f53-902c-00244128e571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.btn.mat-raised-button.mat-button-base.mat-accent.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/app-add-game-form-modal/div/div[2]/div[3]/app-generic-dynamic-form/form/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a853813b-ec87-4a01-aa2b-e7c1d564c8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>accent</value>
      <webElementGuid>3b8acd0e-98f4-4511-83f4-5090a611c0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator btn mat-raised-button mat-button-base mat-accent cdk-focused cdk-mouse-focused</value>
      <webElementGuid>067c3e88-d54d-48f0-90c6-e02a5e438507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>529e4644-d65b-4138-83a9-bfcee0360284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/app-add-game-form-modal[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card rounded-5 shadow-sm bg-dark&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-generic-dynamic-form[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;d-flex action-button&quot;]/button[@class=&quot;mat-focus-indicator btn mat-raised-button mat-button-base mat-accent cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>04604b84-e5c1-431e-9fd2-8ec36e2c7bee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/app-add-game-form-modal/div/div[2]/div[3]/app-generic-dynamic-form/form/div[2]/button</value>
      <webElementGuid>55c1fb75-94dc-458a-b3ba-fb719ecf45dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 4'])[1]/following::button[1]</value>
      <webElementGuid>e57a0a0e-fad3-4b09-8c0e-3b00eb8ef6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Peak ranking'])[1]/following::button[1]</value>
      <webElementGuid>5458b8f6-0f19-4ac2-a77e-b5f423610b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arena of valor'])[2]/preceding::button[1]</value>
      <webElementGuid>0afaf89a-5243-4b04-a7b5-dbfdf215bd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c35bb9fe-e5a6-4fbb-89d3-f156ef43fa7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>98e20edf-00de-458f-834a-859abf3523ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
