<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bronze 0</name>
   <tag></tag>
   <elementGuidId>7d0f54d1-0c87-4dbf-be6a-ca2ee0a08db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#afd45d21db50-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='afd45d21db50-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2734410-43aa-46fa-847a-2796d050a923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted</value>
      <webElementGuid>d485999d-8682-4be5-af14-7ba6fe5a3be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>09a4fda4-22fe-4f14-93c4-ce067f5db59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32da0517-6b73-4cd7-bc7c-00ca30124cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>afd45d21db50-6</value>
      <webElementGuid>7bb8cf17-6c56-4f55-9869-6489af2f05f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bronze 0</value>
      <webElementGuid>1c1d766c-5255-422c-9b1a-7b05f0e7873e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;afd45d21db50-6&quot;)</value>
      <webElementGuid>3a0cca1b-ad39-43dc-a8f1-0e94bcde56bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='afd45d21db50-6']</value>
      <webElementGuid>80fc13e4-8759-44bb-8ec7-3fb0d5eba933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='afd45d21db50']/div/div[2]/div[7]</value>
      <webElementGuid>6a9a6e7d-7aab-46d7-8454-5c535b348f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 5'])[1]/following::div[1]</value>
      <webElementGuid>e105656d-286f-467a-bcbe-0b0ea45c7b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 4'])[1]/following::div[2]</value>
      <webElementGuid>a8ff99f9-9592-407f-b10e-1d22ca02b572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bronze 1'])[1]/preceding::div[1]</value>
      <webElementGuid>307594e5-b312-4b93-91a2-a91223f06efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>94a13c4f-cae4-4042-ab57-39822a7b03d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'afd45d21db50-6' and (text() = 'Bronze 0' or . = 'Bronze 0')]</value>
      <webElementGuid>62026c20-c495-4fbb-b247-fd4bb01710ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
