<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tin 4</name>
   <tag></tag>
   <elementGuidId>83d208c1-e4d3-43f6-ade3-669431c48dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#afd45d21db50-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Tin 4' or . = 'Tin 4')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4c81235-2107-4bbf-9877-7399f74a37c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted</value>
      <webElementGuid>3405cff3-a610-47f3-80b1-468f19bdfa10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f592c057-7034-4f58-8338-f204d711fa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>323b4cca-6f08-423b-a7af-4e8492ffec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>afd45d21db50-4</value>
      <webElementGuid>105efac4-f0e3-427b-9773-d55a45a5f803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tin 4</value>
      <webElementGuid>e496c429-76a4-44b6-b1e2-270f07e539a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;afd45d21db50-4&quot;)</value>
      <webElementGuid>278f52a5-2896-47a8-9579-fcbfab8d8caf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='afd45d21db50-4']</value>
      <webElementGuid>bc4dd735-ab79-455b-8903-f00a84105b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='afd45d21db50']/div/div[2]/div[5]</value>
      <webElementGuid>5ac0b415-a7ca-457a-9b83-635e61f92990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 3'])[1]/following::div[1]</value>
      <webElementGuid>cc4bbb95-1358-42df-b828-ee47fc451f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 2'])[1]/following::div[2]</value>
      <webElementGuid>f081f6a0-d5d7-4b2b-9061-610f2df312f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 5'])[1]/preceding::div[1]</value>
      <webElementGuid>b60259d3-ea9d-4a2e-a44d-28c0b1f48370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[5]</value>
      <webElementGuid>b445e9b9-bed9-4078-bbe8-a60f540d893e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tin 4' or . = 'Tin 4')]</value>
      <webElementGuid>b6c183fc-f621-4b53-b604-a20073534858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
