<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tin 5</name>
   <tag></tag>
   <elementGuidId>969fd8ce-25a1-4538-a195-02de8a8b0180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a3c23104a102-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Tin 5' or . = 'Tin 5')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Tin 5&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6a027d6-cb50-43a6-a587-a7f036b6eb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted</value>
      <webElementGuid>12468d85-00c6-401b-bbcc-06f11e0ec45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8a51050b-0344-4083-9e3e-13e4a1309cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb66b8fa-44bd-4f7b-b461-d469029c7968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a3c23104a102-5</value>
      <webElementGuid>f05322a2-6536-466b-a9cd-95834016de48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tin 5</value>
      <webElementGuid>138d838b-0d22-4065-ae9a-63815abac2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a3c23104a102-5&quot;)</value>
      <webElementGuid>0f2d8db7-fb14-45be-9162-8f6e0d58f8f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a3c23104a102-5']</value>
      <webElementGuid>4a643ef6-c31a-4c98-89ff-57372c9b0bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a3c23104a102']/div/div[2]/div[6]</value>
      <webElementGuid>3a54fe7f-24e2-4f5f-8941-94acc92d68ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 4'])[1]/following::div[1]</value>
      <webElementGuid>9eb50503-bae3-476a-8a5d-7db053cadc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin 3'])[1]/following::div[2]</value>
      <webElementGuid>a4df4b8b-4f12-4209-8a29-e3b4054596ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bronze 0'])[1]/preceding::div[1]</value>
      <webElementGuid>142c9eba-9d39-4b86-8e6b-3890bd49baa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>f9fcebb0-91bf-430a-9c26-8dc4f8ddba90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tin 5' or . = 'Tin 5')]</value>
      <webElementGuid>5edab62b-3380-4f37-89e6-c02c92c3083b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
