<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Xbox</name>
   <tag></tag>
   <elementGuidId>83d03b06-215e-49ef-af5f-b67d6a6f5b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab9dda76c74d-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Xbox' or . = 'Xbox')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Xbox&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f37d2002-16a6-4509-9c03-3b128444cd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted</value>
      <webElementGuid>ab3d7b78-fb99-48d5-9f1f-8e1e492d1e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bf50233f-7f17-4e36-9de0-496088212590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ba73c05-cc59-4d01-952b-6525cebbc672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ab9dda76c74d-2</value>
      <webElementGuid>b0310345-0871-47f3-96fd-0e7a527630f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xbox</value>
      <webElementGuid>6565ebd5-1742-4d00-bc5f-d5aadf9feb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab9dda76c74d-2&quot;)</value>
      <webElementGuid>d755d1bb-d513-4c87-b651-4c054dc751d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ab9dda76c74d-2']</value>
      <webElementGuid>981b931b-656e-4f58-8175-69a6ac2c0ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ab9dda76c74d']/div/div[2]/div[3]</value>
      <webElementGuid>a200babb-c8b3-443b-9fea-c7864c1062ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PS5/4'])[1]/following::div[1]</value>
      <webElementGuid>a2d93b8b-807f-434b-beb3-124c5214d94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC'])[1]/following::div[2]</value>
      <webElementGuid>dfc59315-da22-4738-9b8d-6fbf5163e348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current ranking'])[2]/preceding::div[1]</value>
      <webElementGuid>b2f96775-8b27-44ab-88c0-45db964e0512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[3]</value>
      <webElementGuid>530bb33c-5e71-4749-8b0a-eac2965d8e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Xbox' or . = 'Xbox')]</value>
      <webElementGuid>9865234b-41c9-4712-a587-9a9d4a8fb087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
