<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Characters</name>
   <tag></tag>
   <elementGuidId>f1ad643b-16e8-41c0-a5df-cc369a1ff470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-select-container.ng-appearance-outline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='character']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5db931e7-43fb-4b91-91fe-c8aa6cc7c92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-select-container ng-appearance-outline</value>
      <webElementGuid>51e01f0e-afe5-4adc-9436-6f2b88ea8e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Characters</value>
      <webElementGuid>2541eef8-6c80-4909-bfa1-6676c847b382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;character&quot;)/div[@class=&quot;ng-select-container ng-appearance-outline&quot;]</value>
      <webElementGuid>a3fd0bc8-3581-45a4-a2ca-bf65a73c3b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='character']/div</value>
      <webElementGuid>aaa47d09-354c-4347-9dee-4f997d0cb0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Characters'])[2]/following::div[1]</value>
      <webElementGuid>619cfb80-4d16-40ea-8e99-a446999772ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-game Name'])[2]/following::div[4]</value>
      <webElementGuid>7493efe1-8d32-4895-8a17-2466ee9cffd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BODVAR'])[1]/preceding::div[5]</value>
      <webElementGuid>5589da89-ae31-4dfa-9f67-7588a8f5fcc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div</value>
      <webElementGuid>20505ba2-70f9-4602-a919-9e0d3d8875c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Characters' or . = 'Select Characters')]</value>
      <webElementGuid>c185c7be-281f-48b4-bc5a-41d08e97f44e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
