<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_add</name>
   <tag></tag>
   <elementGuidId>15205c48-3013-4f8a-9649-eb860b1e02bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.add-icon.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='My Games'])[2]/following::mat-icon[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add New Game&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>e5405e3e-4dea-47a8-9110-315a0feb9abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5083164a-c8a0-4d2d-b671-3cea6f099240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate add-icon material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>bbb7c4de-56e2-4092-ba12-32ca87718f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69f0fc90-4149-486c-bdc6-0786b7e1324a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>dcb007c0-0e56-49c7-bf9a-4b19fae6d2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>8b4fa819-a16f-44ee-a82d-eacbe4fef58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;default-theme&quot;]/app-root[1]/app-auth-layout-lg[@class=&quot;default-theme ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-my-profile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mangement-container&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-12&quot;]/app-my-games[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card mb-4 rounded-5 shadow-sm bg-dark&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;game-list&quot;]/div[@class=&quot;game-item ng-star-inserted&quot;]/button[@class=&quot;add-game-btn d-flex flex-column align-items-center justify-content-center game-card add-card add-game-card&quot;]/mat-icon[@class=&quot;mat-icon notranslate add-icon material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>f254ac72-2179-49c0-9de1-06295392b228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Games'])[2]/following::mat-icon[1]</value>
      <webElementGuid>18a44715-b4fb-47ae-b76d-1a65a0548e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social Media'])[1]/following::mat-icon[1]</value>
      <webElementGuid>c7b069f1-82b5-4069-9968-86471ee8ea70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Game'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>cd18aff4-83a3-4bcf-8f0c-b634d69435d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/mat-icon</value>
      <webElementGuid>40edc5d3-df2c-47f4-b695-9ebf5288aa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>a3acd6d8-bada-4601-abc0-ad45f47d2418</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
