<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Single Iframe</name>
   <tag></tag>
   <elementGuidId>18750c0e-2fa5-458d-a9b7-e656518c87c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.analystic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Single Iframe')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Single Iframe&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6fac1fa0-3bc0-4b2f-88c9-40c0b36418df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Single</value>
      <webElementGuid>6f608f2e-69f1-441c-a5da-569df09d4c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b7b27dfd-1bab-4a6a-bcf6-62426c67eb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>analystic</value>
      <webElementGuid>4b5a76d7-9b24-41c5-b3d9-1db12fa9d7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c182d065-fca7-4d0c-8628-bd44a06c57e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single Iframe </value>
      <webElementGuid>18397f47-5eff-42a2-ad8a-5c2e0bc87423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[1]/div[@class=&quot;container center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-xs-offset-2&quot;]/div[@class=&quot;nav nav-tabs&quot;]/div[@class=&quot;col-xs-11 col-xs-offset-1&quot;]/div[@class=&quot;tabpane&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[1]/a[@class=&quot;analystic&quot;]</value>
      <webElementGuid>6592cc41-634e-4226-b821-c568748c0218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Single Iframe')]</value>
      <webElementGuid>11e54864-170c-4ad3-aa28-eeb886f82067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Site'])[1]/following::a[1]</value>
      <webElementGuid>45990cb0-0c06-4209-a285-fa8b1b516742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProgressBar'])[1]/following::a[2]</value>
      <webElementGuid>2ad91a7a-a01d-4bb1-90af-53def1704062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iframe with in an Iframe'])[1]/preceding::a[1]</value>
      <webElementGuid>8f279950-5af3-4077-99b3-f401ebcba9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single Iframe']/parent::*</value>
      <webElementGuid>fd0b54e3-2330-4b96-ad68-dca6ae33a664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Single')]</value>
      <webElementGuid>d53320df-2b61-4b74-ba1f-08ad815cd3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/a</value>
      <webElementGuid>cb1b64fa-3f1b-49a8-94d6-8e8a7713e689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Single' and (text() = 'Single Iframe ' or . = 'Single Iframe ')]</value>
      <webElementGuid>e3523f6e-3676-44c7-bcb2-f4c3660e9388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
